---
title: "Weitere Schritte in R (DOZENTENFASSUNG)"
author: "Norman Markgraf"
date: "23 April 2019"
output: word_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(mosaic)
```

## Der Trinkgeld-Datensatz

Wir laden zu erst den Tipping-Datensatz aus dem Internet 

```{r}
download.file("https://goo.gl/whKjnl", destfile = "tips.csv")
```

Danach laden wir den Datensatz als "tips" in den Speicher:

```{r}
tips <- read.csv2("tips.csv")
```


Die Struktur von tips:

```{r}
str(tips)
```


```{r}
prop( ~ sex, success = "Female", data=tips)
```

```{r}
tally( ~ sex, data=tips)
```

```{r}
tally( ~ sex,
       format = "proportion",
       data=tips)
```


```{r}
gf_bar( ~ sex
        | time,
          data=tips)
```

```{r}
tally( ~ sex
        | time,
          data=tips)
```

```{r}
tally( ~ sex
        | time,
       format = "proportion",
          data=tips)
```



## Vorlesung vom 29.4.2019


## Vorlesung bom 06.05.2019

```{r}
library(mosaic)
tips <- read.csv2("tips.csv")
```


## Offene Übung 61

```{r}
gf_boxplot(total_bill ~ smoker, data=tips)
```

```{r}
gf_histogram(~ total_bill | smoker, data=tips)
```

```{r}
favstats(total_bill ~ smoker, data=tips)
```

```{r}
favstats(~ total_bill | smoker, data=tips)
```

```{r}
iqr(total_bill ~ smoker, data=tips)
```


```{r}
library(mosaic)
set.seed(2009)
muenzverteilung <- do(100) * rflip(n=10)
gf_bar( ~ heads, data=muenzverteilung)
```








